replicaCount: 1
image:
  repository: smartops-bot
  tag: latest
  pullPolicy: IfNotPresent
monitoring:
  enabled: true
  grafana:
    adminPassword: admin
  prometheus:
    enabled: true
securityScan:
  enabled: true
  schedule: "0 * * * *"
n8n:
  webhookUrl: "https://hooks.ferdous.work/webhook/def3c366-c5ca-45ab-ae01-8d6befd8ef00"
