apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mojeeeb/spezielleProg.git
    targetRevision: main
    path: helm/smartops
  destination:
    server: https://kubernetes.default.svc
    namespace: smartops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true